In [1]:
import numpy as np

In [2]:
 x = np.array([])

In [3]:
type(x)

numpy.ndarray

In [4]:
x

array([], dtype=float64)

In [5]:
even = [2,4,6,8,10]

In [6]:
even_array = np.array(even)

In [7]:
even_array

array([ 2,  4,  6,  8, 10])

In [8]:
type(even_array)

numpy.ndarray

In [9]:
#nd means n dimensional array

In [12]:
even_array.ndim ## gives the dimensional of array

1

In [13]:
even_array.shape #length of array

(5,)

In [14]:
len(even_array)

5

#indexing and slicing

In [15]:
x = np.array([3,4,5,6,7,8])

In [16]:
x[3]

6

In [17]:
x[-2]

7

In [19]:
x[4:]

array([7, 8])

In [20]:
x[:5]

array([3, 4, 5, 6, 7])

In [21]:
x[-2:-4]

array([], dtype=int64)

In [22]:
x[-4:-2]

array([5, 6])

#Differnet between list and array
*Array operation are faster than the list that means array is faster than list .