In [ ]:
!pip install numpy

#installing numpy


#Importing Numpy

In [ ]:
import numpy as np

#creating an empty array

In [ ]:
x = np.array([])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x

array([], dtype=float64)

#create an array an even Numbers

In [ ]:
even = [ 2, 4, 88,4,32,2]

In [ ]:
even_array = np.array(even)

In [ ]:
even_array

array([ 2,  4, 88,  4, 32,  2])

In [ ]:
type(even_array)

numpy.ndarray

In [ ]:
#nd means n-dimensional

In [ ]:
even_array.ndim #ndim gives no of dimensions;this is 1 dimensional array

1

In [ ]:
even_array.shape #(length_of_ array, )

(6,)

In [ ]:
len(even_array)

6

#indexing and slicing

In [ ]:
x = np.array([5,9,3,7,44,21,0,2,3])

In [ ]:
x[3]

7

In [ ]:
x[6]

0

In [ ]:
x[-3] #negative indexing

0

In [ ]:
x[4:7]#slicing

array([44, 21,  0])

In [ ]:
x[0:4]


array([5, 9, 3, 7])

In [ ]:
x[-4:]

array([21,  0,  2,  3])

#Different between list and array

* Array operation are faster than list operation which means array is faster than list.
* List support multiple datatype in constrast, array supports homogenous data type
* Array are memory efficient than List

In [ ]:
#data type

In [ ]:
L1 = [True, "hello",55,33.1]
type(L1[0])

bool

In [ ]:
L1_array = np. array(L1)
L1_array

array(['True', 'hello', '55', '33.1'], dtype='<U32')

In [ ]:
type(L1_array[0])

numpy.str_

#Random number Generation

In [ ]:
np.random.randint(1,10)

7

In [ ]:
np.random.seed(4)
np.random.randint(1,10)

8

In [ ]:
x_array = np.random.randint(low=1, high=10, size = 50000)
x_array

array([6, 2, 9, ..., 1, 6, 2])

In [ ]:
len(x_array)

50000

In [ ]:
x_list = x_array.tolist()#typecasting array to list

In [ ]:
type(x_list)

list

In [ ]:
%%time
sq = [item ** 2 for item in x_list]#list operation

CPU times: user 16.1 ms, sys: 0 ns, total: 16.1 ms
Wall time: 17.8 ms


In [ ]:
%%time
sq = x_array ** 2 #array operation

CPU times: user 997 µs, sys: 0 ns, total: 997 µs
Wall time: 938 µs


#Array is memory effiecent

In [21]:
import numpy as np

In [2]:
even = np.array([50, 6, 2, 20] , dtype = np.int8)
even

array([50,  6,  2, 20], dtype=int8)

In [7]:
even = np.array([50, 6, 2, 20] , dtype = np.int16)
even

array([50,  6,  2, 20], dtype=int16)

#zeros(),ones() and empty()

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.ones(3, dtype = np.int8)

array([1, 1, 1], dtype=int8)

In [13]:
np.empty(15) #empty depends on mempry

array([5.04287660e-310, 0.00000000e+000, 1.01855798e-312, 9.54898106e-313,
       1.10343781e-312, 1.01855798e-312, 1.23075756e-312, 1.18831764e-312,
       1.06099790e-312, 9.76118064e-313, 1.12465777e-312, 1.03977794e-312,
       1.14587773e-312, 6.67219137e-310, 6.32404027e-322])

In [14]:
#Zeros and pnes are used in binary image masking



#.arange()

In [15]:
np .arange(start=0, stop=5, step= 1)

array([0, 1, 2, 3, 4])

In [16]:
list( range(0,5,1))

[0, 1, 2, 3, 4]

#.linspace()

In [17]:
np.linspace(start=0, stop=1, num=5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [18]:
#zero dekhi 1 sama 5 ota number generate garne with equal spacing

#sort()and concatenate()

In [24]:
x = np.array([2,3,4,5,6,7,1,8,9,-3])

In [25]:
np.sort(x)

array([-3,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [27]:
np.flip(np.sort(x))

array([ 9,  8,  7,  6,  5,  4,  3,  2,  1, -3])

In [28]:
x = np.array([5,6])
y = np.array([1,2,3])

In [29]:
[5,3] + [1,2,3] #you can concatenate list using + operator

[5, 3, 1, 2, 3]

In [31]:
np.concatenate([x,y])


array([5, 6, 1, 2, 3])

#vector operation and broadcasting

In [32]:
x = np.array([8,9])
y = np.array([2,3])

In [33]:
x + y

array([10, 12])

In [34]:
x - y

array([6, 6])

In [35]:
x*y

array([16, 27])

In [36]:
#Do rest at home of arthmatic operation

In [37]:
3 + x #Broadcasting


array([11, 12])

#. any() vs.all()

In [39]:
np.random.seed()
x = np.random.randint(low=1, high=7,size=10)
x

array([5, 5, 6, 2, 3, 2, 1, 6, 6, 6])

In [40]:
x >= 5

array([ True,  True,  True, False, False, False, False,  True,  True,
        True])

In [41]:
np.any(x>= 5)

True

In [42]:
np.all(x>=5)

False

In [43]:
x [x>=5]

array([5, 5, 6, 6, 6, 6])

In [44]:
x[x==1 or x==6]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
x[(x==1) | (x==6)] #bitwise or

array([6, 1, 6, 6, 6])

In [47]:
x[(x>2) & (x>6)]#Bitwise and

array([], dtype=int64)

#statistics using numpy

In [48]:
np.random.seed(0)
x = np.random.randint(1, 100,size = 50)
x

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88, 71, 89, 89, 13, 59, 66, 40,
       88, 47, 89, 82, 38, 26, 78, 73, 10, 21, 81, 70, 80, 48, 65, 83, 89,
       50, 30, 20, 20, 15, 40, 33, 66, 10, 58, 33, 32, 75, 24, 36, 76])

In [49]:
np.mean(x)


52.96

In [50]:
x.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [52]:
np.median(x)

54.0

In [56]:
np.var(x)

659.9584

In [57]:
np.std(x)

25.689655505669982

In [58]:
np.min(x)

10

In [59]:
np.max(X)

NameError: name 'X' is not defined

In [61]:
from scipy.stats import mode
mode(x)

ModeResult(mode=89, count=4)

In [68]:
x = np.array([3,55,5,2,34])

In [69]:
np.max(x)

55

In [70]:
#max 55 ho esko index kati ho tw?
np.argmax(x)

1

In [71]:
np.min(x)

2

In [72]:
np.argmin(x)

3

#2D array


In [1]:
import numpy as np

In [2]:
matrix = np.array ([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
matrix.shape

(3, 3)

In [5]:
matrix.ndim

2

In [6]:
matrix[1,1]

5

In [7]:
matrix[1,2]

6

In [8]:
matrix[0,2]

3

In [9]:
matrix[2,0]

7

In [10]:
matrix[2,2]

9

In [11]:
matrix[1,2]

6

In [14]:
matrix[:,2]

array([3, 6, 9])

In [15]:
matrix[: ,0]

array([1, 4, 7])

In [16]:
matrix[1, :]

array([4, 5, 6])

In [17]:
matrix[1: ,1:]

array([[5, 6],
       [8, 9]])

In [18]:
matrix[0:2 ,:2]

array([[1, 2],
       [4, 5]])

In [19]:
matrix[:2 ,1:]

array([[2, 3],
       [5, 6]])

#Dot Product, matrix multiplication -linear algebra

In [32]:
A = np.array([[1,2,3,],[4,5,6]])
B = np.array([[7,8],[9,10],[11,12]])

In [23]:
a.shape

NameError: name 'a' is not defined

In [24]:
A.shape

(2, 3)

In [25]:
B.Shape


AttributeError: 'numpy.ndarray' object has no attribute 'Shape'

In [26]:
B.shape

(3, 2)

In [27]:
output

NameError: name 'output' is not defined

In [28]:
output = np.(AB)

SyntaxError: invalid syntax (<ipython-input-28-2e0ef6304f12>, line 1)

In [30]:
output = np.dot(AB)

NameError: name 'AB' is not defined

In [33]:
output = np.dot(A,B)

In [34]:
np.linalg.det(output)

36.000000000000256

In [ ]:
np.round()

#The axis argument in numpy:2D axis =0 is column-wise and axis = 10 means row-wise

In [35]:
matrix = np.array([[4,5,6],[7,8,9]])
matrix.shape

(2, 3)

In [36]:
matrix

array([[4, 5, 6],
       [7, 8, 9]])

In [37]:
matrix.sum() #4+5+6+7+8+9

39

In [38]:
matrix.sum(axis = 0) #Vertically sum

array([11, 13, 15])

In [44]:
matrix.sum(axis = 1) #horizontally

array([15, 24])

#.flatten()

In [46]:
matrix = np.array([[4,5,6],[7,8,9]])
matrix #2D array

array([[4, 5, 6],
       [7, 8, 9]])

In [47]:
matrix.flatten() #1D

array([4, 5, 6, 7, 8, 9])

#.reshape()

In [48]:
x = np.array([2,3,4,5,6,7])

In [49]:
x

array([2, 3, 4, 5, 6, 7])

In [50]:
x.reshape(2,3)

array([[2, 3, 4],
       [5, 6, 7]])

In [51]:
x.shape(3,2)

TypeError: 'tuple' object is not callable

In [52]:
x.reshape(3,2)

array([[2, 3],
       [4, 5],
       [6, 7]])

In [53]:
row_matrix = x.reshape(1, -1)
print(row_matrix)
row_matrix.shape

[[2 3 4 5 6 7]]


(1, 6)

In [54]:
colum_matrix = x.reshape(-1,1)

In [55]:
print(colum_matrix)
colum_matrix

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]


array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [57]:
colum_matrix.shape

(6, 1)